### ISSUE TITLE
Display toymaker ID when gift is sent

### ISSUE THREAD

**Issue by FreezyExp** [nightzirch/secret-toymaker.web#102]
**Is your feature request related to a problem? Please describe.**
When you are sent a gift but did not receive it, it would be nice to be able to contact the toymaker to remind them to hit send.

This would also make a mark as received reminder to the giftee (sometimes they forget).
As they might have received some or multiple donations and now they do not know which one to mark as received.

**Describe the solution you'd like**
Once a gift or donation is marked as sent, it also displays whom it was sent by.
Similar to receiving the name of the person you are gifting to.

**Describe alternatives you've considered**
Waiting around, getting angry and dissapointed in fellow humans abusing this wonderfull wintersday organization.

Contacting Arenanet to see if they can streamline this process a bit, like an API that can reply yes/no to a "has received a message from X, that then also shows the items attached to each message". This would allow for incident reports to be fairly judged with complete transparancy (some people will try to trick the system with an empty message). The text would not need to be visible as that would fall within the normal anet community moderation.

**Additional context**
I think that removing the anonimity of the gifter is a moot point, if they did in fact send something you receive a in-game e-mail from them.

**Comment by FreezyExp** [comment]
It is sad that it feels like this is even neccesary, but there are people out there that abuse systems like this.
Building protections, checks and balances into the system is the only way to ensure fair and charitable gifting runs smoothly.

**Comment by FreezyExp** [comment]
I must have missed that it was there all along

**Comment by nightzirch** [comment]
> I must have missed that it was there all along

This was introduced this year. So great minds think alike 😄 The idea was that the secret aspect of the gifting is gone  once you receive a gift and the toymaker is revealed. It doesn't make sense to hide the account name of the toymaker anymore. However, that only applies when the gift is marked as sent; not just received.
